<?php $e = static fn (mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); $editing = !empty($category); ?>
<div class="container mx-auto p-6"><a href="/admin/faq/categories" class="text-sm font-semibold text-blue-700">← Torna alle categorie FAQ</a><h1 class="my-6 text-3xl font-semibold"><?= $editing ? 'Modifica categoria FAQ' : 'Nuova categoria FAQ' ?></h1>
<form method="post" action="<?= $editing ? '/admin/faq/categories/' . (int) $category['id'] . '/update' : '/admin/faq/categories/store' ?>" class="space-y-5 rounded-xl bg-white p-6 shadow">
	<input type="hidden" name="csrf_token" value="<?= $e($csrf_token) ?>">
	<div><label for="name" class="mb-1 block font-semibold">Nome *</label><input id="name" name="name" required maxlength="150" value="<?= $e($category['name'] ?? '') ?>" class="w-full rounded-lg border p-3"></div>
	<div><label for="slug" class="mb-1 block font-semibold">Slug SEO</label><input id="slug" name="slug" maxlength="160" value="<?= $e($category['slug'] ?? '') ?>" placeholder="Generato dal nome se vuoto" class="w-full rounded-lg border p-3"></div>
	<div><label for="description" class="mb-1 block font-semibold">Descrizione</label><textarea id="description" name="description" maxlength="500" rows="3" class="w-full rounded-lg border p-3"><?= $e($category['description'] ?? '') ?></textarea></div>
	<div class="grid gap-5 sm:grid-cols-2"><div><label for="feature_flag_key" class="mb-1 block font-semibold">Visibile quando</label><select id="feature_flag_key" name="feature_flag_key" class="w-full rounded-lg border p-3"><option value="">Sempre visibile</option><?php foreach ($flags as $flag): ?><option value="<?= $e($flag['flag_key']) ?>" <?= ($category['feature_flag_key'] ?? '') === $flag['flag_key'] ? 'selected' : '' ?>><?= $e($flag['label']) ?></option><?php endforeach; ?></select><p class="mt-1 text-xs text-gray-500">La categoria sparisce se la funzionalità selezionata è disattivata.</p></div><div><label for="sort_order" class="mb-1 block font-semibold">Ordine</label><input id="sort_order" name="sort_order" type="number" min="0" value="<?= (int) ($category['sort_order'] ?? 0) ?>" class="w-full rounded-lg border p-3"></div></div>
	<label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" <?= !isset($category) || (int) ($category['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><span>Categoria pubblicata</span></label>
	<button class="rounded-lg bg-green-600 px-5 py-3 font-semibold text-white hover:bg-green-700">Salva categoria</button>
</form></div>
