<?php $e = static fn (mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); $editing = !empty($item); ?>
<div class="container mx-auto p-6"><a href="/admin/faq/items" class="text-sm font-semibold text-blue-700">← Torna a domande e risposte</a><h1 class="my-6 text-3xl font-semibold"><?= $editing ? 'Modifica domanda e risposta' : 'Nuova domanda e risposta' ?></h1>
<form method="post" action="<?= $editing ? '/admin/faq/items/' . (int) $item['id'] . '/update' : '/admin/faq/items/store' ?>" class="space-y-5 rounded-xl bg-white p-6 shadow">
	<input type="hidden" name="csrf_token" value="<?= $e($csrf_token) ?>">
	<div><label for="category_id" class="mb-1 block font-semibold">Categoria *</label><select id="category_id" name="category_id" required class="w-full rounded-lg border p-3"><option value="">Seleziona</option><?php foreach ($categories as $category): ?><option value="<?= (int) $category['id'] ?>" <?= (int) ($item['category_id'] ?? 0) === (int) $category['id'] ? 'selected' : '' ?>><?= $e($category['name']) ?></option><?php endforeach; ?></select></div>
	<div><label for="question" class="mb-1 block font-semibold">Domanda *</label><input id="question" name="question" required maxlength="255" value="<?= $e($item['question'] ?? '') ?>" class="w-full rounded-lg border p-3"></div>
	<div><label for="answer" class="mb-1 block font-semibold">Risposta *</label><textarea id="answer" name="answer" required rows="9" class="w-full rounded-lg border p-3"><?= $e($item['answer'] ?? '') ?></textarea><p class="mt-1 text-xs text-gray-500">Testo semplice: i ritorni a capo saranno mantenuti.</p></div>
	<div class="grid gap-5 sm:grid-cols-2"><div><label for="feature_flag_key" class="mb-1 block font-semibold">Visibile quando</label><select id="feature_flag_key" name="feature_flag_key" class="w-full rounded-lg border p-3"><option value="">Eredita la categoria</option><?php foreach ($flags as $flag): ?><option value="<?= $e($flag['flag_key']) ?>" <?= ($item['feature_flag_key'] ?? '') === $flag['flag_key'] ? 'selected' : '' ?>><?= $e($flag['label']) ?></option><?php endforeach; ?></select></div><div><label for="sort_order" class="mb-1 block font-semibold">Ordine</label><input id="sort_order" name="sort_order" type="number" min="0" value="<?= (int) ($item['sort_order'] ?? 0) ?>" class="w-full rounded-lg border p-3"></div></div>
	<label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" <?= !isset($item) || (int) ($item['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><span>FAQ pubblicata</span></label>
	<button class="rounded-lg bg-green-600 px-5 py-3 font-semibold text-white hover:bg-green-700">Salva FAQ</button>
</form></div>
