<?php
$organizations = $data['organizations'] ?? [];
$claims = $data['claims'] ?? [];
$roles = ['owner' => 'Proprietario', 'admin' => 'Amministratore', 'editor' => 'Editor', 'viewer' => 'Visualizzatore'];
$statuses = ['pending' => 'In attesa', 'approved' => 'Approvata', 'rejected' => 'Rifiutata', 'cancelled' => 'Annullata'];
$h = static fn ($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
?>
<main class="mx-auto max-w-6xl space-y-6">
    <header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wide text-green-900">Gestione organizzazioni</p><h1 class="mt-2 text-3xl font-extrabold text-gray-950">Le mie organizzazioni</h1><p class="mt-2 text-gray-700">Gestisci le organizzazioni di cui fai parte e segui le richieste di gestione inviate.</p></div><a href="/dashboard/organizations/create" class="rounded-lg bg-green-800 px-4 py-3 font-bold text-white">Crea nuova organizzazione</a></header>
    <section class="rounded-2xl bg-white p-5 shadow-sm md:p-6"><div class="space-y-3"><?php foreach ($organizations as $organization): ?><a href="/dashboard/organizations/<?= (int) $organization['id'] ?>" class="block rounded-xl border border-gray-200 p-4 hover:border-green-300"><div class="flex flex-wrap items-center justify-between gap-2"><h2 class="font-bold text-gray-950"><?= $h($organization['name']) ?></h2><span class="text-sm font-semibold text-green-900"><?= $h($roles[$organization['role']] ?? $organization['role']) ?></span></div><p class="mt-2 text-sm text-gray-600"><?= (int) $organization['master_count'] ?> master · <?= (int) $organization['member_count'] ?> membri</p></a><?php endforeach; ?><?php if (!$organizations): ?><p class="text-sm text-gray-600">Non fai ancora parte di nessuna organizzazione.</p><?php endif; ?></div></section>
    <section class="rounded-2xl bg-white p-5 shadow-sm md:p-6"><h2 class="text-xl font-bold text-gray-950">Le mie richieste</h2><div class="mt-4 space-y-3"><?php foreach ($claims as $claim): ?><div class="rounded-xl border border-gray-200 p-4"><div class="flex flex-wrap items-center justify-between gap-2"><a href="/eventi-master/<?= rawurlencode((string) $claim['event_master_slug']) ?>" class="font-bold text-green-900 hover:underline"><?= $h($claim['event_master_name']) ?></a><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700"><?= $h($statuses[$claim['status']] ?? $claim['status']) ?></span></div><p class="mt-2 text-sm text-gray-600"><?= $h($claim['organization_name']) ?></p><?php if (!empty($claim['review_notes'])): ?><p class="mt-2 text-sm text-gray-500">Nota dello staff: <?= $h($claim['review_notes']) ?></p><?php endif; ?></div><?php endforeach; ?><?php if (!$claims): ?><p class="mt-4 text-sm text-gray-600">Non hai ancora inviato richieste.</p><?php endif; ?></div></section>
</main>
