<?php use App\Core\Session; $master = $master ?? []; $regions = $regions ?? []; $types = $types ?? []; ?>
<div class="mx-auto max-w-6xl p-6">
	<a href="/dashboard/organizations/<?php echo (int) $organizationId; ?>/masters/<?php echo (int) $master['id']; ?>" class="font-semibold text-green-800">← Torna al master</a>
	<h1 class="mt-5 text-3xl font-bold">Crea nuova edizione</h1>
	<p class="mt-1 text-slate-500">Master: <?php echo htmlspecialchars($master['nome'] ?? ''); ?></p>
	<?php if ($message = Session::getFlash('error')): ?><div class="mt-4 rounded-lg bg-red-100 p-4 text-red-800"><?php echo htmlspecialchars($message); ?></div><?php endif; ?>
	<div id="dashboard-event-create-feedback" class="mt-4 hidden rounded-lg p-4 text-sm"></div>
	<form class="mt-6 space-y-5 rounded-2xl bg-white p-6 shadow" action="/dashboard/organizations/<?php echo (int) $organizationId; ?>/masters/<?php echo (int) $master['id']; ?>/events/create" method="post">
		<input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token'] ?? ''); ?>">
		<input type="hidden" name="guest_ids" id="create-event-guest-ids" value="[]">
		<div class="grid gap-5 md:grid-cols-2">
			<label class="font-semibold">Titolo<input required class="mt-1 w-full rounded-lg border p-3" name="titolo"></label>
			<label class="font-semibold md:max-w-[150px]">Anno<input required type="number" min="2000" max="2100" class="mt-1 w-full rounded-lg border p-3" name="anno" value="<?php echo date('Y'); ?>"></label>
			<label class="font-semibold">Luogo<input required class="mt-1 w-full rounded-lg border p-3" name="luogo"></label>
			<label class="font-semibold md:max-w-[220px]">Data inizio<input required type="date" class="mt-1 w-full rounded-lg border p-3" name="data_inizio"></label>
			<label class="font-semibold md:max-w-[220px]">Data fine<input type="date" class="mt-1 w-full rounded-lg border p-3" name="data_fine"></label>
			<label class="font-semibold">Regione<select required class="mt-1 w-full rounded-lg border p-3" name="regione_id" id="create-event-region"><option value="">Seleziona regione</option><?php foreach ($regions as $region): ?><option value="<?php echo (int) $region['id']; ?>"><?php echo htmlspecialchars($region['nome']); ?></option><?php endforeach; ?></select></label>
			<label class="font-semibold">Provincia<select required class="mt-1 w-full rounded-lg border p-3" name="provincia_id" id="create-event-province"><option value="">Seleziona provincia</option></select></label>
			<label class="font-semibold">Comune<select required class="mt-1 w-full rounded-lg border p-3" name="comune_id" id="create-event-municipality"><option value="">Seleziona comune</option></select></label>
			<label class="font-semibold">Tipo evento<select required class="mt-1 w-full rounded-lg border p-3" name="tipo_evento_id"><option value="">Seleziona tipo</option><?php foreach ($types as $type): ?><option value="<?php echo (int) $type['id']; ?>"><?php echo htmlspecialchars($type['nome']); ?></option><?php endforeach; ?></select></label>
		</div>
		<div><label for="create-event-description" class="font-semibold">Descrizione</label><div id="create-event-description" class="mt-1 min-h-48 rounded-lg border bg-white"></div></div>
		<div class="grid gap-5 md:grid-cols-2"><label class="font-semibold">Sito web<input type="url" class="mt-1 w-full rounded-lg border p-3" name="sito_web"></label><label class="font-semibold">Facebook<input type="url" class="mt-1 w-full rounded-lg border p-3" name="social_facebook"></label><label class="font-semibold">Instagram<input type="url" class="mt-1 w-full rounded-lg border p-3" name="social_instagram"></label><label class="font-semibold">YouTube<input type="url" class="mt-1 w-full rounded-lg border p-3" name="social_youtube"></label></div>
		<div class="flex flex-wrap gap-6"><label><input type="checkbox" name="is_paid" value="1"> Evento a pagamento</label><label><input type="checkbox" name="has_cosplay_contest" value="1"> Contest cosplay</label></div>
		<section class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-bold">Ospiti evento</h2><button type="button" id="create-event-new-guest" class="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">+ Nuovo ospite</button></div><div class="relative mt-3"><input id="create-event-guest-search" type="search" autocomplete="off" placeholder="Cerca ospite..." class="w-full rounded-lg border p-3"><div id="create-event-guest-results" class="absolute z-10 hidden max-h-60 w-full overflow-auto rounded-lg border bg-white shadow"></div></div><div id="create-event-selected-guests" class="mt-4 flex flex-wrap gap-2"></div></section>
		<div class="flex justify-end"><button class="rounded-lg bg-green-700 px-5 py-3 font-bold text-white" type="submit">Crea edizione</button></div>
	</form>
</div>
<script src="/public_assets/js/wysiwyg-editor.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
	WysiwygEditor.init('#create-event-description', { content: '', name: 'descrizione', placeholder: "Scrivi la descrizione dell'edizione..." });
	const region = document.getElementById('create-event-region'), province = document.getElementById('create-event-province'), municipality = document.getElementById('create-event-municipality');
	region.addEventListener('change', async function () { province.innerHTML = '<option value="">Caricamento province...</option>'; municipality.innerHTML = '<option value="">Seleziona comune</option>'; const rows = await (await fetch('/api/province/' + encodeURIComponent(region.value))).json(); province.innerHTML = '<option value="">Seleziona provincia</option>'; rows.forEach(row => province.insertAdjacentHTML('beforeend', '<option value="' + Number(row.id) + '">' + String(row.nome).replace(/&/g, '&amp;').replace(/</g, '&lt;') + '</option>')); });
	province.addEventListener('change', async function () { municipality.innerHTML = '<option value="">Caricamento comuni...</option>'; const rows = await (await fetch('/api/comuni/' + encodeURIComponent(province.value))).json(); municipality.innerHTML = '<option value="">Seleziona comune</option>'; rows.forEach(row => municipality.insertAdjacentHTML('beforeend', '<option value="' + Number(row.id) + '">' + String(row.nome).replace(/&/g, '&amp;').replace(/</g, '&lt;') + '</option>')); });
	const form = document.querySelector('form'), feedback = document.getElementById('dashboard-event-create-feedback');
	let selectedGuests = [];
	const guestSearch = document.getElementById('create-event-guest-search');
	const guestResults = document.getElementById('create-event-guest-results');
	const guestBox = document.getElementById('create-event-selected-guests');
	const guestIds = document.getElementById('create-event-guest-ids');
	function renderGuests() { guestBox.innerHTML = ''; selectedGuests.forEach(function (guest) { const item = document.createElement('span'); item.className = 'inline-flex items-center gap-2 rounded-full bg-blue-100 px-3 py-1 text-sm text-blue-800'; item.textContent = guest.name; const remove = document.createElement('button'); remove.type = 'button'; remove.textContent = '×'; remove.className = 'font-bold'; remove.addEventListener('click', function () { selectedGuests = selectedGuests.filter(function (row) { return Number(row.id) !== Number(guest.id); }); renderGuests(); }); item.appendChild(remove); guestBox.appendChild(item); }); guestIds.value = JSON.stringify(selectedGuests.map(function (guest) { return Number(guest.id); })); }
	let guestTimer;
	guestSearch.addEventListener('input', function () { clearTimeout(guestTimer); guestResults.innerHTML = ''; guestResults.classList.add('hidden'); if (guestSearch.value.trim().length < 2) return; guestTimer = setTimeout(async function () { const response = await fetch('/dashboard/guests/search?q=' + encodeURIComponent(guestSearch.value.trim()), { headers: { Accept: 'application/json' } }); const payload = await response.json(); guestResults.classList.remove('hidden'); (payload.guests || []).forEach(function (guest) { const option = document.createElement('button'); option.type = 'button'; option.className = 'block w-full px-3 py-2 text-left hover:bg-slate-50'; option.textContent = guest.name; option.addEventListener('click', function () { if (!selectedGuests.some(function (row) { return Number(row.id) === Number(guest.id); })) selectedGuests.push(guest); renderGuests(); guestSearch.value = ''; guestResults.classList.add('hidden'); }); guestResults.appendChild(option); }); }, 250); });
	document.getElementById('create-event-new-guest').addEventListener('click', async function () { const name = window.prompt('Nome del nuovo guest:'); if (!name || name.trim().length < 2) return; const body = new FormData(); body.append('name', name.trim()); body.append('csrf_token', '<?php echo htmlspecialchars($_SESSION['csrf_token'] ?? '', ENT_QUOTES); ?>'); const response = await fetch('/dashboard/guests/create', { method: 'POST', body: body, headers: { Accept: 'application/json' } }); const payload = await response.json(); if (!response.ok || !payload.success) { window.alert(payload.message || 'Guest non creato.'); return; } selectedGuests.push(payload.guest); renderGuests(); });
	renderGuests();
	form.addEventListener('submit', async function (event) { event.preventDefault(); const button = form.querySelector('button[type="submit"]'); button.disabled = true; try { const response = await fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Creazione non riuscita.'); feedback.textContent = result.message; feedback.className = 'mt-4 rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800'; form.reset(); } catch (error) { feedback.textContent = error.message || 'Creazione non riuscita.'; feedback.className = 'mt-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800'; } finally { button.disabled = false; } });
});
</script>
