CREATE TABLE IF NOT EXISTS ad_positions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    page VARCHAR(100) NOT NULL,
    description TEXT NULL,
    width INT NULL,
    height INT NULL,
    mobile_width INT NULL,
    mobile_height INT NULL,
    max_slots INT NOT NULL DEFAULT 1,
    rotation_type ENUM('random','weighted','fixed') NOT NULL DEFAULT 'random',
    base_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    min_days INT NOT NULL DEFAULT 7,
    max_days INT NOT NULL DEFAULT 60,
    estimated_monthly_impressions INT NULL,
    average_ctr DECIMAL(5,2) NULL,
    is_sponsored_rel_required TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ad_positions_active (is_active, sort_order),
    INDEX idx_ad_positions_page (page)
);

CREATE TABLE IF NOT EXISTS ad_position_prices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    position_id INT NOT NULL,
    duration_days INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_ad_position_duration (position_id, duration_days),
    INDEX idx_ad_position_prices_active (position_id, is_active),
    CONSTRAINT fk_ad_position_prices_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ad_banners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    image_path VARCHAR(255) NULL,
    mobile_image_path VARCHAR(255) NULL,
    logo_path VARCHAR(255) NULL,
    target_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(255) NULL,
    sponsor_name VARCHAR(150) NULL,
    facebook_url VARCHAR(500) NULL,
    instagram_url VARCHAR(500) NULL,
    tiktok_url VARCHAR(500) NULL,
    creative_type ENUM('image','sponsor_card','html_safe') NOT NULL DEFAULT 'image',
    type ENUM('internal','sponsor','test') NOT NULL DEFAULT 'sponsor',
    status ENUM('draft','pending_review','approved','rejected') NOT NULL DEFAULT 'draft',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ad_banners_user (user_id),
    INDEX idx_ad_banners_status (status, is_active),
    CONSTRAINT fk_ad_banners_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ad_campaigns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    position_id INT NOT NULL,
    banner_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    status ENUM(
        'draft',
        'reserved',
        'pending_payment',
        'payment_failed',
        'pending_approval',
        'changes_requested',
        'scheduled',
        'active',
        'paused',
        'expired',
        'cancelled',
        'refunded'
    ) NOT NULL DEFAULT 'draft',
    approval_status ENUM('not_required','pending','approved','rejected','changes_requested') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    admin_notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ad_campaigns_user (user_id),
    INDEX idx_ad_campaigns_position_dates (position_id, start_date, end_date),
    INDEX idx_ad_campaigns_status (status, approval_status),
    CONSTRAINT fk_ad_campaigns_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_campaigns_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ad_campaigns_banner FOREIGN KEY (banner_id) REFERENCES ad_banners(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ad_reservations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    position_id INT NOT NULL,
    campaign_id INT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reserved_slots INT NOT NULL DEFAULT 1,
    price DECIMAL(10,2) NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    status ENUM('reserved','expired','converted','cancelled') NOT NULL DEFAULT 'reserved',
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ad_reservations_position_dates (position_id, start_date, end_date),
    INDEX idx_ad_reservations_status_expiry (status, expires_at),
    CONSTRAINT fk_ad_reservations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ad_reservations_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_reservations_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ad_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    reservation_id INT NULL,
    campaign_id INT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    vat DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    status ENUM('draft','pending_payment','paid','failed','cancelled','refunded') NOT NULL DEFAULT 'draft',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at DATETIME NULL,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ad_orders_user (user_id),
    INDEX idx_ad_orders_status (status),
    CONSTRAINT fk_ad_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_orders_reservation FOREIGN KEY (reservation_id) REFERENCES ad_reservations(id) ON DELETE SET NULL,
    CONSTRAINT fk_ad_orders_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ad_payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NULL,
    campaign_id INT NOT NULL,
    provider VARCHAR(50) NOT NULL DEFAULT 'adyen',
    provider_reference VARCHAR(255) NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
    status ENUM('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
    paid_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ad_payments_campaign (campaign_id),
    INDEX idx_ad_payments_order (order_id),
    INDEX idx_ad_payments_provider_reference (provider_reference),
    CONSTRAINT fk_ad_payments_order FOREIGN KEY (order_id) REFERENCES ad_orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_ad_payments_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ad_impressions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    banner_id INT NOT NULL,
    position_id INT NOT NULL,
    page VARCHAR(100) NULL,
    device_type ENUM('desktop','mobile','tablet','bot','unknown') NOT NULL DEFAULT 'unknown',
    country_code CHAR(2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ad_impressions_campaign_date (campaign_id, created_at),
    INDEX idx_ad_impressions_banner_date (banner_id, created_at),
    INDEX idx_ad_impressions_position_date (position_id, created_at),
    INDEX idx_ad_impressions_created (created_at),
    CONSTRAINT fk_ad_impressions_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_impressions_banner FOREIGN KEY (banner_id) REFERENCES ad_banners(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_impressions_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ad_clicks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    banner_id INT NOT NULL,
    position_id INT NOT NULL,
    page VARCHAR(100) NULL,
    target_url VARCHAR(500) NULL,
    referrer VARCHAR(255) NULL,
    device_type ENUM('desktop','mobile','tablet','bot','unknown') NOT NULL DEFAULT 'unknown',
    country_code CHAR(2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ad_clicks_campaign_date (campaign_id, created_at),
    INDEX idx_ad_clicks_banner_date (banner_id, created_at),
    INDEX idx_ad_clicks_position_date (position_id, created_at),
    INDEX idx_ad_clicks_created (created_at),
    CONSTRAINT fk_ad_clicks_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_clicks_banner FOREIGN KEY (banner_id) REFERENCES ad_banners(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_clicks_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ad_stats_daily (
    id INT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    position_id INT NOT NULL,
    date DATE NOT NULL,
    impressions INT NOT NULL DEFAULT 0,
    clicks INT NOT NULL DEFAULT 0,
    unique_clicks INT NOT NULL DEFAULT 0,
    desktop_impressions INT NOT NULL DEFAULT 0,
    mobile_impressions INT NOT NULL DEFAULT 0,
    tablet_impressions INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_stat (campaign_id, position_id, date),
    INDEX idx_ad_stats_daily_position_date (position_id, date),
    CONSTRAINT fk_ad_stats_daily_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_ad_stats_daily_position FOREIGN KEY (position_id) REFERENCES ad_positions(id) ON DELETE CASCADE
);
