CREATE TABLE IF NOT EXISTS `photo_analytics_events` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `event_type` VARCHAR(60) NOT NULL,
  `visitor_key` CHAR(64) NOT NULL,
  `user_id` INT NULL,
  `event_id` INT NULL,
  `photo_id` BIGINT UNSIGNED NULL,
  `uploaded_by_user_id` INT NULL,
  `source` VARCHAR(40) NULL,
  `filter_event_id` INT NULL,
  `filter_year` SMALLINT UNSIGNED NULL,
  `filter_uploader_id` INT NULL,
  `request_path` VARCHAR(255) NULL,
  `referrer` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_photo_analytics_type_date` (`event_type`, `created_at`),
  KEY `idx_photo_analytics_visitor_date` (`visitor_key`, `created_at`),
  KEY `idx_photo_analytics_event_type_date` (`event_id`, `event_type`, `created_at`),
  KEY `idx_photo_analytics_photo_type_date` (`photo_id`, `event_type`, `created_at`),
  KEY `idx_photo_analytics_uploader_type_date` (`uploaded_by_user_id`, `event_type`, `created_at`),
  KEY `idx_photo_analytics_filters` (`filter_event_id`, `filter_year`, `filter_uploader_id`),
  CONSTRAINT `fk_photo_analytics_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_photo_analytics_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_photo_analytics_photo` FOREIGN KEY (`photo_id`) REFERENCES `photos` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_photo_analytics_uploader` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
