CREATE TABLE IF NOT EXISTS `legacy_photo_imports` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `source` VARCHAR(80) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `destination_user_id` INT NOT NULL,
  `total_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `valid_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `processed_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `imported_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `skipped_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `error_records` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('analyzed','ready','processing','paused','completed','completed_with_errors','error') NOT NULL DEFAULT 'analyzed',
  `summary_json` JSON NULL,
  `mapping_json` JSON NULL,
  `created_by_user_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  KEY `idx_legacy_photo_imports_status` (`status`),
  KEY `idx_legacy_photo_imports_user` (`destination_user_id`),
  CONSTRAINT `fk_legacy_photo_imports_destination_user` FOREIGN KEY (`destination_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_legacy_photo_imports_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `legacy_photo_import_items` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `import_id` BIGINT UNSIGNED NOT NULL,
  `legacy_source` VARCHAR(80) NOT NULL,
  `legacy_id` BIGINT UNSIGNED NOT NULL,
  `legacy_title` VARCHAR(255) NULL,
  `legacy_author` VARCHAR(255) NULL,
  `legacy_published_at` DATETIME NULL,
  `legacy_event_name` VARCHAR(255) NULL,
  `legacy_event_year` SMALLINT UNSIGNED NULL,
  `original_url` VARCHAR(1000) NOT NULL,
  `thumbnail_url` VARCHAR(1000) NULL,
  `legacy_detail_url` VARCHAR(1000) NULL,
  `legacy_views` INT UNSIGNED NULL,
  `legacy_favorites` INT UNSIGNED NULL,
  `target_event_id` INT NULL,
  `status` ENUM('pending','processing','imported','imported_without_event','skipped_already_imported','blocked_event_mapping','error') NOT NULL DEFAULT 'pending',
  `photo_id` BIGINT UNSIGNED NULL,
  `error_code` VARCHAR(80) NULL,
  `error_message` VARCHAR(500) NULL,
  `locked_at` DATETIME NULL,
  `processed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  UNIQUE KEY `uniq_legacy_photo_import_item` (`import_id`, `legacy_source`, `legacy_id`),
  KEY `idx_legacy_photo_items_status` (`import_id`, `status`, `locked_at`),
  KEY `idx_legacy_photo_items_legacy` (`legacy_source`, `legacy_id`),
  KEY `idx_legacy_photo_items_event` (`target_event_id`),
  CONSTRAINT `fk_legacy_photo_items_import` FOREIGN KEY (`import_id`) REFERENCES `legacy_photo_imports` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_legacy_photo_items_event` FOREIGN KEY (`target_event_id`) REFERENCES `events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_legacy_photo_items_photo` FOREIGN KEY (`photo_id`) REFERENCES `photos` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `legacy_photo_mappings` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `legacy_source` VARCHAR(80) NOT NULL,
  `legacy_id` BIGINT UNSIGNED NOT NULL,
  `photo_id` BIGINT UNSIGNED NOT NULL,
  `legacy_detail_url` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_legacy_photo_mapping` (`legacy_source`, `legacy_id`),
  UNIQUE KEY `uniq_legacy_photo_mapping_photo` (`photo_id`),
  CONSTRAINT `fk_legacy_photo_mappings_photo` FOREIGN KEY (`photo_id`) REFERENCES `photos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
