CREATE TABLE IF NOT EXISTS `email_delivery_events` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `provider` VARCHAR(32) NOT NULL DEFAULT 'brevo',
    `message_id` VARCHAR(255) NOT NULL,
    `webhook_id` BIGINT UNSIGNED DEFAULT NULL,
    `event_name` VARCHAR(64) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `subject` VARCHAR(255) DEFAULT NULL,
    `tag` VARCHAR(100) DEFAULT NULL,
    `tags_json` TEXT DEFAULT NULL,
    `template_id` BIGINT UNSIGNED DEFAULT NULL,
    `reason` VARCHAR(1000) DEFAULT NULL,
    `sending_ip` VARCHAR(45) DEFAULT NULL,
    `ts_event` BIGINT UNSIGNED DEFAULT NULL,
    `ts_epoch` BIGINT UNSIGNED DEFAULT NULL,
    `event_date` DATETIME DEFAULT NULL,
    `raw_payload_json` LONGTEXT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_email_delivery_event` (`provider`, `message_id`, `event_name`, `ts_event`),
    KEY `idx_email_delivery_events_email` (`email`),
    KEY `idx_email_delivery_events_tag_date` (`tag`, `event_date`),
    KEY `idx_email_delivery_events_event_date` (`event_name`, `event_date`),
    KEY `idx_email_delivery_events_message` (`message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
