<?php
$h = static fn ($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$statuses = ['draft' => 'Bozza', 'pending_review' => 'In revisione', 'active' => 'Attiva', 'suspended' => 'Sospesa', 'archived' => 'Archiviata'];
?>
<div class="container mx-auto max-w-6xl p-6" data-organization-page>
    <div class="mb-6 flex flex-wrap gap-3"><a href="/admin/organizations" class="rounded-lg bg-gray-200 px-4 py-2 font-semibold text-gray-800">Torna alle organizzazioni</a><a href="/admin/organizations/<?= (int) $organization['id'] ?>/edit" class="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Modifica organizzazione</a></div>
    <h1 class="text-3xl font-semibold text-gray-800"><?= $h($organization['name']) ?></h1><p class="mb-6 text-gray-500">Owner: <?= $h($organization['owner_username'] ?? 'N/D') ?></p>
    <div data-feedback class="mb-4 hidden rounded-xl px-4 py-3 text-sm"></div>

    <nav class="mb-6 flex gap-2 border-b border-gray-200" aria-label="Sezioni organizzazione">
        <button type="button" data-tab-button="data" class="border-b-2 border-green-800 px-4 py-3 text-sm font-semibold text-green-900">Dati organizzazione</button>
        <button type="button" data-tab-button="management" class="border-b-2 border-transparent px-4 py-3 text-sm font-semibold text-gray-500">Gestione</button>
    </nav>

    <section data-tab-panel="data" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200">
        <h2 class="text-xl font-bold">Dati organizzazione</h2>
        <form data-ajax-form method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/update" enctype="multipart/form-data" class="mt-4 grid gap-5 md:grid-cols-2">
            <input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>">
            <div><label for="organization-name" class="block text-sm font-semibold">Nome</label><input id="organization-name" name="name" required maxlength="180" value="<?= $h($organization['name'] ?? '') ?>" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"></div>
            <div><label for="organization-owner" class="block text-sm font-semibold">Owner</label><select id="organization-owner" name="owner_user_id" required class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"><option value="">Seleziona utente</option><?php foreach ($users as $user): ?><option value="<?= (int) $user['id'] ?>" <?= (int) ($organization['owner_user_id'] ?? 0) === (int) $user['id'] ? 'selected' : '' ?>><?= $h($user['username']) ?> (<?= $h($user['email']) ?>)</option><?php endforeach; ?></select></div>
            <div><label for="organization-email" class="block text-sm font-semibold">Email</label><input id="organization-email" type="email" name="email" maxlength="255" value="<?= $h($organization['email'] ?? '') ?>" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"></div>
            <div><label for="organization-website" class="block text-sm font-semibold">Sito web</label><input id="organization-website" type="url" name="website_url" maxlength="500" value="<?= $h($organization['website_url'] ?? '') ?>" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"></div>
            <div><label for="organization-logo" class="block text-sm font-semibold">Immagine principale</label><input id="organization-logo" type="file" name="logo" accept="image/jpeg,image/png,image/webp" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"><p class="mt-1 text-xs text-gray-500">Logo o immagine principale. JPG, PNG o WebP.</p><?php if (!empty($organization['logo_path'])): ?><img src="/public_assets<?= $h($organization['logo_path']) ?>" alt="Immagine principale <?= $h($organization['name']) ?>" class="mt-3 h-24 w-24 rounded-xl border border-gray-200 object-cover"><?php endif; ?></div>
            <div><label for="organization-cover" class="block text-sm font-semibold">Cover</label><input id="organization-cover" type="file" name="cover" accept="image/jpeg,image/png,image/webp" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"><p class="mt-1 text-xs text-gray-500">Immagine orizzontale per pagina pubblica e anteprime.</p><?php if (!empty($organization['cover_path'])): ?><img src="/public_assets<?= $h($organization['cover_path']) ?>" alt="Cover <?= $h($organization['name']) ?>" class="mt-3 h-24 w-full rounded-xl border border-gray-200 object-cover"><?php endif; ?></div>
            <div class="md:col-span-2"><label for="organization-description" class="block text-sm font-semibold">Descrizione</label><textarea id="organization-description" name="description" rows="5" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2"><?= $h($organization['description'] ?? '') ?></textarea></div>
            <label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_public" value="1" <?= !empty($organization['is_public']) ? 'checked' : '' ?>> Pubblica organizzazione</label>
            <div class="md:col-span-2"><button class="rounded-lg bg-green-800 px-5 py-3 font-semibold text-white">Salva dati</button></div>
        </form>
    </section>

    <div data-tab-panel="management" class="hidden">
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold">Stato</h2><form data-ajax-form method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/status" class="mt-4 flex flex-wrap gap-3"><input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>"><select name="status" class="flex-1 rounded-lg border px-3 py-2"><?php foreach ($statuses as $key => $label): ?><option value="<?= $key ?>" <?= $organization['status'] === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select><button class="rounded-lg bg-green-800 px-4 py-2 font-semibold text-white">Salva stato</button></form></section>

    <section class="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold">Associa membro</h2><p class="mt-1 text-sm text-gray-500">Cerca per username o email e seleziona un risultato.</p><form data-ajax-form data-refresh-members method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/members/add" class="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>"><div class="relative min-w-[260px] flex-1" data-user-typeahead><label for="organization-user-search" class="mb-1 block text-sm font-semibold text-gray-700">Utente</label><input id="organization-user-search" type="search" data-user-search autocomplete="off" placeholder="Username o email" class="w-full rounded-lg border px-3 py-2" aria-autocomplete="list" aria-controls="organization-user-results"><input type="hidden" name="user_id" data-user-id required><div id="organization-user-results" data-user-results class="absolute z-10 mt-1 hidden max-h-60 w-full overflow-auto rounded-lg border border-gray-200 bg-white shadow-lg" role="listbox"></div><p data-user-selected class="mt-1 hidden text-sm text-green-800"></p></div><select name="role" class="rounded-lg border px-3 py-2"><option value="admin">Amministratore</option><option value="editor">Editor</option><option value="viewer">Visualizzatore</option></select><button class="rounded-lg bg-green-800 px-4 py-2 font-semibold text-white">Associa</button></form></section>

    <section data-members-panel class="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold">Membri e accessi</h2><div class="mt-4 space-y-3"><?php foreach ($organization['members'] as $member): ?><form data-ajax-form method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/members/update" class="flex flex-wrap items-center gap-3 border-b border-gray-100 pb-3"><input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>"><input type="hidden" name="user_id" value="<?= (int) $member['user_id'] ?>"><span class="min-w-[180px] flex-1 text-sm font-semibold"><?= $h($member['username']) ?> <span class="font-normal text-gray-400">(<?= $h($member['email']) ?>)</span></span><?php if ((int) $member['user_id'] === (int) $organization['owner_user_id']): ?><span class="text-sm font-semibold text-gray-600">Proprietario</span><?php else: ?><select name="role" class="rounded-lg border px-3 py-2 text-sm"><option value="admin" <?= $member['role'] === 'admin' ? 'selected' : '' ?>>Amministratore</option><option value="editor" <?= $member['role'] === 'editor' ? 'selected' : '' ?>>Editor</option><option value="viewer" <?= $member['role'] === 'viewer' ? 'selected' : '' ?>>Visualizzatore</option></select><select name="status" class="rounded-lg border px-3 py-2 text-sm"><option value="active" <?= $member['status'] === 'active' ? 'selected' : '' ?>>Attivo</option><option value="removed" <?= $member['status'] === 'removed' ? 'selected' : '' ?>>Rimosso</option></select><button class="rounded-lg bg-gray-800 px-3 py-2 text-sm font-semibold text-white">Salva</button><?php endif; ?></form><?php endforeach; ?></div></section>

    <section class="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold">Associa master</h2><p class="mt-1 text-sm text-gray-500">Cerca il master per nome e seleziona un risultato.</p><form data-ajax-form data-refresh-masters method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/masters/add" class="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>"><div class="relative min-w-[260px] flex-1" data-master-typeahead><label for="organization-master-search" class="mb-1 block text-sm font-semibold text-gray-700">Master</label><input id="organization-master-search" type="search" data-master-search autocomplete="off" placeholder="Nome del master" class="w-full rounded-lg border px-3 py-2" aria-autocomplete="list" aria-controls="organization-master-results"><input type="hidden" name="event_master_id" data-master-id required><div id="organization-master-results" data-master-results class="absolute z-10 mt-1 hidden max-h-60 w-full overflow-auto rounded-lg border border-gray-200 bg-white shadow-lg" role="listbox"></div><p data-master-selected class="mt-1 hidden text-sm text-green-800"></p></div><select name="role" class="rounded-lg border px-3 py-2"><option value="organizer">Organizzatore</option><option value="co_organizer">Co-organizzatore</option></select><button class="rounded-lg bg-green-800 px-4 py-2 font-semibold text-white">Associa</button></form></section>

    <section data-masters-panel class="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 class="text-xl font-bold">Master collegati</h2><div class="mt-4 space-y-3"><?php foreach ($organization['masters'] as $master): ?><form data-ajax-form method="POST" action="/admin/organizations/<?= (int) $organization['id'] ?>/masters/update" class="flex flex-wrap items-center gap-3 border-b border-gray-100 pb-3"><input type="hidden" name="csrf_token" value="<?= $h($csrf_token) ?>"><input type="hidden" name="event_master_id" value="<?= (int) $master['event_master_id'] ?>"><a class="min-w-[220px] flex-1 font-semibold text-green-900 hover:underline" href="/admin/events-master/edit/<?= (int) $master['event_master_id'] ?>"><?= $h($master['nome']) ?></a><select name="role" class="rounded-lg border px-3 py-2 text-sm"><option value="organizer" <?= $master['role'] === 'organizer' ? 'selected' : '' ?>>Organizzatore</option><option value="co_organizer" <?= $master['role'] === 'co_organizer' ? 'selected' : '' ?>>Co-organizzatore</option></select><button class="rounded-lg bg-gray-800 px-3 py-2 text-sm font-semibold text-white">Salva</button><button type="button" data-remove-master class="rounded-lg bg-red-700 px-3 py-2 text-sm font-semibold text-white">Rimuovi</button></form><?php endforeach; ?><?php if (!$organization['masters']): ?><p class="text-sm text-gray-500">Nessun master collegato.</p><?php endif; ?></div></section>
    </div>
</div>
<script>
(function () {
    const page = document.querySelector('[data-organization-page]'); if (!page) return;
    const feedback = page.querySelector('[data-feedback]');
    const show = (message, ok) => { feedback.textContent = message; feedback.className = 'mb-4 rounded-xl px-4 py-3 text-sm ' + (ok ? 'border border-green-200 bg-green-50 text-green-800' : 'border border-red-200 bg-red-50 text-red-800'); };
    const setTab = (name) => { page.querySelectorAll('[data-tab-panel]').forEach((panel) => panel.classList.toggle('hidden', panel.dataset.tabPanel !== name)); page.querySelectorAll('[data-tab-button]').forEach((button) => { const active = button.dataset.tabButton === name; button.classList.toggle('border-green-800', active); button.classList.toggle('text-green-900', active); button.classList.toggle('border-transparent', !active); button.classList.toggle('text-gray-500', !active); }); history.replaceState(null, '', '#' + name); };
    page.querySelectorAll('[data-tab-button]').forEach((button) => button.addEventListener('click', () => setTab(button.dataset.tabButton)));
    setTab(window.location.hash === '#data' ? 'data' : 'management');
    const refreshPanels = async () => { const response = await fetch(window.location.href, { headers: { Accept: 'text/html' } }); const doc = new DOMParser().parseFromString(await response.text(), 'text/html'); ['members', 'masters'].forEach((name) => { const current = page.querySelector('[data-' + name + '-panel]'); const next = doc.querySelector('[data-' + name + '-panel]'); if (current && next) current.replaceWith(next); }); bindForms(); bindMasterRemovals(); };
    const bindForms = () => page.querySelectorAll('[data-ajax-form]').forEach((form) => { if (form.dataset.bound) return; form.dataset.bound = '1'; form.addEventListener('submit', async (event) => { event.preventDefault(); const button = form.querySelector('button:not([type="button"])'); if (button) button.disabled = true; try { const selectedUser = form.querySelector('[data-user-id]'); const selectedMaster = form.querySelector('[data-master-id]'); if (selectedUser && !selectedUser.value) throw new Error('Seleziona un utente dai risultati della ricerca.'); if (selectedMaster && !selectedMaster.value) throw new Error('Seleziona un master dai risultati della ricerca.'); const response = await fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Operazione non riuscita.'); show(result.message || 'Operazione completata.', true); if (form.closest('[data-members-panel]') || form.closest('[data-masters-panel]') || form.hasAttribute('data-refresh-members') || form.hasAttribute('data-refresh-masters')) await refreshPanels(); } catch (error) { show(error.message || 'Operazione non riuscita.', false); } finally { if (button) button.disabled = false; } }); });
    const bindMasterRemovals = () => page.querySelectorAll('[data-remove-master]').forEach((button) => { if (button.dataset.bound) return; button.dataset.bound = '1'; button.addEventListener('click', async () => { const form = button.closest('form'); if (!form || !window.confirm('Rimuovere questo master dall’organizzazione?')) return; button.disabled = true; try { const response = await fetch('/admin/organizations/<?= (int) $organization['id'] ?>/masters/remove', { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Operazione non riuscita.'); show(result.message, true); await refreshPanels(); } catch (error) { show(error.message || 'Operazione non riuscita.', false); button.disabled = false; } }); });
    const typeahead = page.querySelector('[data-user-typeahead]');
    if (typeahead) {
        const input = typeahead.querySelector('[data-user-search]'); const userId = typeahead.querySelector('[data-user-id]'); const results = typeahead.querySelector('[data-user-results]'); const selected = typeahead.querySelector('[data-user-selected]'); let timer; let controller;
        const clearSelection = () => { userId.value = ''; selected.textContent = ''; selected.classList.add('hidden'); };
        const closeResults = () => { results.innerHTML = ''; results.classList.add('hidden'); };
        const renderResults = (users) => { results.innerHTML = ''; if (!users.length) { const empty = document.createElement('p'); empty.className = 'px-3 py-2 text-sm text-gray-500'; empty.textContent = 'Nessun utente trovato.'; results.appendChild(empty); } else users.forEach((user) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'block w-full px-3 py-2 text-left text-sm hover:bg-gray-50'; button.setAttribute('role', 'option'); button.textContent = user.username + ' (' + user.email + ')'; button.addEventListener('click', () => { userId.value = user.id; input.value = user.username; selected.textContent = 'Selezionato: ' + user.username + ' (' + user.email + ')'; selected.classList.remove('hidden'); closeResults(); }); results.appendChild(button); }); results.classList.remove('hidden'); };
        input.addEventListener('input', () => { clearSelection(); clearTimeout(timer); if (controller) controller.abort(); const query = input.value.trim(); if (query.length < 2) return closeResults(); timer = setTimeout(async () => { controller = new AbortController(); try { const response = await fetch('/admin/organizations/<?= (int) $organization['id'] ?>/users/search?q=' + encodeURIComponent(query), { headers: { Accept: 'application/json' }, signal: controller.signal }); const payload = await response.json(); if (response.ok && payload.success) renderResults(payload.users || []); } catch (error) { if (error.name !== 'AbortError') closeResults(); } }, 250); });
        input.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeResults(); }); document.addEventListener('click', (event) => { if (!typeahead.contains(event.target)) closeResults(); });
    }
    const masterTypeahead = page.querySelector('[data-master-typeahead]');
    if (masterTypeahead) {
        const input = masterTypeahead.querySelector('[data-master-search]'); const masterId = masterTypeahead.querySelector('[data-master-id]'); const results = masterTypeahead.querySelector('[data-master-results]'); const selected = masterTypeahead.querySelector('[data-master-selected]'); let timer; let controller;
        const clearSelection = () => { masterId.value = ''; selected.textContent = ''; selected.classList.add('hidden'); };
        const closeResults = () => { results.innerHTML = ''; results.classList.add('hidden'); };
        const renderResults = (masters) => { results.innerHTML = ''; if (!masters.length) { const empty = document.createElement('p'); empty.className = 'px-3 py-2 text-sm text-gray-500'; empty.textContent = 'Nessun master trovato.'; results.appendChild(empty); } else masters.forEach((master) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'block w-full px-3 py-2 text-left text-sm hover:bg-gray-50'; button.setAttribute('role', 'option'); button.textContent = master.nome; button.addEventListener('click', () => { masterId.value = master.id; input.value = master.nome; selected.textContent = 'Selezionato: ' + master.nome; selected.classList.remove('hidden'); closeResults(); }); results.appendChild(button); }); results.classList.remove('hidden'); };
        input.addEventListener('input', () => { clearSelection(); clearTimeout(timer); if (controller) controller.abort(); const query = input.value.trim(); if (query.length < 2) return closeResults(); timer = setTimeout(async () => { controller = new AbortController(); try { const response = await fetch('/admin/organizations/<?= (int) $organization['id'] ?>/masters/search?q=' + encodeURIComponent(query), { headers: { Accept: 'application/json' }, signal: controller.signal }); const payload = await response.json(); if (response.ok && payload.success) renderResults(payload.masters || []); } catch (error) { if (error.name !== 'AbortError') closeResults(); } }, 250); });
        input.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeResults(); }); document.addEventListener('click', (event) => { if (!masterTypeahead.contains(event.target)) closeResults(); });
    }
    bindForms(); bindMasterRemovals();
})();
</script>
